### PR TITLE
Update the import paths for Caddy

### PR DESCRIPTION
**Pull request by ghost**
This pull request makes caddy-custom-auth compatible with Caddy v1.0.1+ (see epicagency/caddy-expires#6 for reference) by updating the import paths for Caddy.

### CODE REVIEW

**Comment by whalehub** [comment]
@michele Could you please have a look at this PR?

**Comment by whalehub** [comment]
Closed due to inactivity.

**Comment by michele** [comment]
@whalehub Sorry for not getting back earlier, but I thought I was the only one using this. I'll gladly apply this change.

**Comment by michele** [comment]
@whalehub I just wanted to let you know I've updated the plugin. Thanks for taking the time to write the PR and sorry again for the delay.

**Pull request closed without merging**
